name: "webmin.dev: webmin/webmin"

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: webmin/webmin-ci-cd/.github/workflows/testing-master-workflow.yml@master
    with:
      build-type: package
      project-name: webmin
